# Generated by Django 4.2.23 on 2025-08-14 19:58

import datetime
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_thumbnail_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 19, 58, 45, 910271, tzinfo=datetime.timezone.utc)),
        ),
    ]
