# Generated by Django 4.2.23 on 2025-08-14 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 21, 0, 5, 762399, tzinfo=datetime.timezone.utc)),
        ),
    ]
