# Generated by Django 4.2.23 on 2025-08-14 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 21, 8, 5, 424073, tzinfo=datetime.timezone.utc)),
        ),
    ]
