# Generated by Django 4.2.23 on 2025-08-15 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_created_at_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 15, 6, 59, 37, 17976, tzinfo=datetime.timezone.utc)),
        ),
    ]
