# Generated by Django 4.2.23 on 2025-08-30 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 30, 23, 5, 9, 493427, tzinfo=datetime.timezone.utc)),
        ),
    ]
