# Generated by Django 4.2.23 on 2025-09-07 03:34

import apps.blog.models
import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(storage=core.storage_backends.PublicMediaStorage(), upload_to=apps.blog.models.blog_thumbanil_directory),
        ),
    ]
